### ISSUE TITLE
Do not mention on lockscreen that Yubikey is needed

### ISSUE THREAD

**Issue by MarcMichalsky** [cornelinux/yubikey-luks#11]
Is it possible to change the lockscreen text, which mentions that in addition to a password a *Yubikey* is needed?

If someone finds out your password and the lockscreen tells him that he will also need your *Yubikey* to login, he could force you to hand it over to him. As an improvement of security there should be an option to remove this message from lockscreen.

Thanks!

**Comment by cornelinux** [comment]
The text is in ``/usr/share/yubikey-luks/ykluks-keyscript``. Currently you can not change the text by any configuration. You would have to change it in the script itself.

**Comment by MarcMichalsky** [comment]
Ok, thanks a lot!
