### ISSUE TITLE
Concatenate challenge + response into LUKS passphrase

### ISSUE THREAD

**Issue by Vincent43** [cornelinux/yubikey-luks#15]
Currently only response for a challenge is used as LUKS passphrase which makes user provided challenge/password redundant in case of bruteforce attack. Also yubikey responses have limited character set, i.e. `bd438575f4e8df965c80363f8aa6fe1debbe9ea9` (no uppercase).

Combining provided challenge **with** response as LUKS passphrase will increase its security without any downsides.

Before:
`LUKS passphrase=bd438575f4e8df965c80363f8aa6fe1debbe9ea9`
After:
`LUKS passphrase=PaSwOrDbd438575f4e8df965c80363f8aa6fe1debbe9ea9`

**Comment by cornelinux** [comment]
I think the basic idea, to add another component to the yubikey response makes totally sense.
We need to figure out, which would be the best one.

**Comment by Vincent43** [comment]
Thanks for the reply. Adding password/challenge would be definitely the easiest as it's already available in current scheme.
