### ISSUE TITLE
ubuntu server with zfsonlinux and raid-1

### ISSUE THREAD

**Issue by tristan-k** [cornelinux/yubikey-luks#3]
Hi there,

I'm runing a home server with ubuntu 14.04 lts and native zfs. There are two luks encrpyted hdds in a raid-1 structure (mirror). The hdds will be auto opened (decrypted and mounted) with a keyfile on startup. To achieve better security I want the drive only to be opened when my yubikey is attached and after a password is entered. Is this possible with your solution? If so, how? 

Regards

**Comment by cornelinux** [comment]
Closing it for no response.
