### ISSUE TITLE
Hex to binary?

### ISSUE THREAD

**Issue by skyrider456** [cornelinux/yubikey-luks#34]
I might be reading the code wrong, but in its current form isn't this creating the passphrase using an ascii representation of the hex code output from the Yubikey? Doesn't that need to get [converted to binary](https://stackoverflow.com/questions/1604765/linux-shell-scripting-hex-string-to-bytes) before being used as a key? As it is now, I think the passphrase is using a long string of ascii characters [0-9] and [a-f] (lowercase) rather than an actual binary string.

**Comment by Vincent43** [comment]
Yubikey output (response) is always in `HMAC-SHA1` format and it's not further modified.  User password is optionally hashed with `SHA-256` and concatenated with yubikey response.

**Comment by cornelinux** [comment]
@skyrider456  thanks for asking. @Vincent43  thanks for commenting.
I see no necessary action here, so I will close this issue.
If you think otherwise, please comment.
