### ISSUE TITLE
Initramfs hook does not start on boot

### ISSUE THREAD

**Issue by LucaZulberti** [cornelinux/yubikey-luks#37]
With the new Ubuntu 18.10, the hook script does not start anymore.
The cryptsetup hook is called and I have to enter the password manually.

I've tried to purge and reinstall the package, but nothing has happened.

**Comment by LucaZulberti** [comment]
Thank you! But I think the correct way to fix that bug is pointed out by the "cryptsetup" maintainer in that bugreport:

In `/etc/crypttab`:
`sda3-crypt      UUID=<uuid>       none    luks,keyscript=/usr/share/yubikey-luks/ykluks-keyscript`

**Comment by Vincent43** [comment]
Did you tested this? I don't think `/usr/share/yubikey-luks/ykluks-keyscript` exist in initramfs image. Perhaps it may look like: `sda3-crypt UUID=<uuid> none luks,keyscript=/sbin/ykluks-keyscript` but I didn't confirmed if it works.

**Comment by Vincent43** [comment]
I researched it further and it seems that systemd still doesn't support `keyscript` parameter in crypptab:
https://bugs.launchpad.net/ubuntu/+source/systemd/+bug/1451032
https://github.com/systemd/systemd/pull/3007

However it seems to be possible to pass it from boot cmdline:
https://news.ycombinator.com/item?id=8477913

You may try something like this:
`cryptopts=source=/dev/<disk>,target=sda3-crypt,keyscript=/sbin/ykluks-keyscript`

**Comment by LucaZulberti** [comment]
I've tried your first solution (patch to local-top script) and then my solution, both are working.

If I use /sbin/ykluks-keyscript, the update-initramfs reports that the value for keyring option is invalid.

Tomorrow I will investigate further too.

**Comment by LucaZulberti** [comment]
> Did you tested this? I don't think `/usr/share/yubikey-luks/ykluks-keyscript` exist in initramfs image.

In `/lib/crypsetup/functions/` file the parser searches for keyscript in the current filesytem, not in initramfs image.
At line 186, I have:
```
        keyscript)
            [ -n "${VALUE:+x}" ] || return 1 # must have a value
            if [ "${VALUE#/}" = "$VALUE" ]; then
                VALUE="/lib/cryptsetup/scripts/$VALUE"
            fi
            if [ ! -x "$VALUE" ] || [ ! -f "$VALUE" ]; then
                return 1
            fi
        ;;
```

In `/usr/share/initramfs-tools/hooks/cryptroot` file seems that the keyscripts are copied with the same path of original file.

At line 205:
```
    if [ -n "${CRYPTTAB_OPTION_keyscript+x}" ]; then
        copy_exec "$CRYPTTAB_OPTION_keyscript"
    fi
```

So it seems reasonable to use the same path in `keyscript` option.

**Comment by Vincent43** [comment]
Thanks, that's interesting and makes things simpler. Maybe we could radically simplify current config. I'll look at this.

**Comment by Vincent43** [comment]
I tested this and confirmed that it can work in to ways:

Adding `sda3-crypt UUID=<uuid> none luks,keyscript=/usr/share/yubikey-luks/ykluks-keyscript` in `/etc/crypttab`.

or

Adding  `cryptopts=source=UUID=<uuid>,target=sda3-crypt,keyscript=/sbin/ykluks-keyscript` to boot params.
