### ISSUE TITLE
Feature Request: Simpler way to manage more than one key

### ISSUE THREAD

**Issue by markfaine** [cornelinux/yubikey-luks#5]
Is there a simpler way to add an additional yubikey.  I'd like a backup yubikey but privacyidea seems like overkill.  I'd like to have the ability to simply add another yubikey.

**Comment by cornelinux** [comment]
Why don't you use

   -s <slot> 

There you can put different yubikeys in each slot?

**Comment by markfaine** [comment]
Thanks, I'll look into that. I thought I had tried that already but maybe
I'm mistaken.
