### ISSUE TITLE
Password exposed in process list

### ISSUE THREAD

**Issue by HacKanCuBa** [cornelinux/yubikey-luks#51]
Hello there! I was checking your scripts and I noticed that you pass the password to the `ykchalresp` bin as part of its command line, thus exposing it to the system: https://github.com/cornelinux/yubikey-luks/blob/5df2b95c30fc963bc76291de487b5654e558baf9/yubikey-luks-enroll#L77

If you run `top` or `htop` you will see the password shows up there. The same happens in the initram script, but on that scenario is not so dangerous. However, on the already booted up scenario, having the password shown as part of the command is VERY dangerous.

I haven't used `ykchalresp` but a better approach would be to pass the password like: `printf "%s" "$P1" | ykchalresp -2 -` or something like that (we need to test this).

**Comment by conn** [comment]
Using [hidepid](https://linux-audit.com/linux-system-hardening-adding-hidepid-to-proc/) might be a way to mitigate this. This is likely mostly a risk with multi-user systems. Since you have code that probably works, why don't you try making a PR to fix this?

**Comment by Vincent43** [comment]
Not everyone want to devote time for PR if [it end up sitting there along the rest](https://github.com/cornelinux/yubikey-luks/pulls). You may prepare one yourself if you wish, [here's example of what needs to be done](https://github.com/agherzan/yubikey-full-disk-encryption/commit/6aa15b9ddc9ce3d6f2fc1aa6b79842d4afe76f83).

**Comment by HacKanCuBa** [comment]
> Using [hidepid](https://linux-audit.com/linux-system-hardening-adding-hidepid-to-proc/) might be a way to mitigate this. This is likely mostly a risk with multi-user systems. Since you have code that probably works, why don't you try making a PR to fix this?

`hidepid` would be more of a *band-aid* rather than a solution. And not only other users can observe the process list, but *every other process can*, meaning a malicious process could retrieve sensitive information, even if it's running with the lowest possible system privileges. Or worst, imagine a bug in a web browser...

Anyway, as Vincent mentioned, I won't issue a PR just for it to sit waiting but I've no problem in doing it as long as the maintainer comes and asks me for it :)

**Comment by conn** [comment]
> hidepid would be more of a band-aid rather than a solution. And not only other users can observe the process list, but every other process can, meaning a malicious process could retrieve sensitive information, even if it's running with the lowest possible system privileges. Or worst, imagine a bug in a web browser...

That's exactly the problem that `hidepid` solves. Mounting `/proc` with `hidepid` makes it so that users can only see their own processes and their particulars, save for root.

`ykchalresp` takes the challenge as an argument, so there's really no way to avoid leaking it through the process list; you'll have to patch `ykchalresp` to take the challenge interactively.

`hidepid` is an easy and useful layer of security to add to your host. I'm sure there are other instances where it would prevent leaking sensitive information.

**Comment by Vincent43** [comment]
> That's exactly the problem that hidepid solves. Mounting /proc with hidepid makes it so that users can only see their own processes and their particulars, save for root.

hidepid doesn't solve problem of spying by other processes of the same user. That was the point.

> ykchalresp takes the challenge as an argument, so there's really no way to avoid leaking it through the process list; you'll have to patch ykchalresp to take the challenge interactively.

Nope, it can take it from STDIN which could be passed through pipe. This is exact solution I linked above.

**Comment by conn** [comment]
> hidepid doesn't solve problem of spying by other processes of the same user. That was the point.

'yubikey-luks-enroll` needs to run as root. If you don't trust root with seeing its own processes, then you have bigger problems.

> Nope, it can take it from STDIN which could be passed through pipe. This is exact solution I linked above.

I didn't catch that before. To be pedantic, `printf` is not a builtin so it and its arguments will still land on the process tree. That being said, it's a good solution since it'll be too fast to catch:

```bash
time printf %s secret

secret
real	0m0.000s
user	0m0.000s
sys	0m0.000s
```

I concede

**Comment by Vincent43** [comment]
> To be pedantic, printf is not a builtin so it and its arguments will still land on the process tree

Well it **is a builtin** in bash,dash,yash,zsh so you have to be very, very pedantic to claim it isn't :smile:

**Comment by conn** [comment]
> Well it is a builtin in bash,dash,yash,ksh,zsh so you have to be very, very pedantic to claim it isn't 😄
```bash
# which printf
/usr/bin/printf
```

It's part of `coreutils` 😉 
https://www.gnu.org/software/coreutils/manual/html_node/printf-invocation.html#printf-invocation

**Comment by conn** [comment]
It's part of the `busybox` `coreutils` implementation as well:
https://git.busybox.net/busybox/tree/coreutils/printf.c

**Comment by Vincent43** [comment]
>  which printf
> /usr/bin/printf

```
$ type printf
printf is a shell builtin
```
https://www.gnu.org/software/bash/manual/html_node/Bash-Builtins.html
I hope this makes thing clear.

**Comment by conn** [comment]
It does! I see what you mean. In which instances is one used over the other?

**Comment by Vincent43** [comment]
Built-ins always take precedence over external commands. If you want to use external command then use full path like `/usr/bin/printf`. You can check if command is built-in and the order with `type -a xxx` (The oder is top (highest) - botttom (lowest).

**Comment by conn** [comment]
Brilliant. Thanks for explaining that! I've got nothing. Your stuff is good.

**Comment by CDSRV** [comment]
https://github.com/Yubico/yubikey-personalization/search?q=getenv&unscoped_q=getenv

https://github.com/Yubico/yubikey-personalization/blob/master/ykchalresp.c

ykchalresp could support reading an environment variable, but it only reads from stdin

**Comment by Vincent43** [comment]
@CDSRV exporting secret in environment is as bad as passing it as commandline argument, just run `ps ewwax` to see this. Piping stdin is proper solution.

**Comment by HacKanCuBa** [comment]
I agree on not using env vars unless the user is fully aware that the secret would be exposed. As vincent said, piping is the way to go :)

**Comment by mansoor-yousefi** [comment]
What's the point of challenge response in encryption? You basically brute force both the passphrase and the secret key in Yubikey. If you want to add to your password, just add a static password. This has the advantage that user's passphrase is not handled by an add-on program inappropriately, as noted above. 

Can one store a key file in Yubikey and use that as the second part? Like static password but not printed on screen.
