### ISSUE TITLE
yubikey-luks-open command not working

### ISSUE THREAD

**Issue by bungabunga** [cornelinux/yubikey-luks#53]
I made a LUKS container protected with yubikey-luks that I want to open on a running system but the yubikey-luks-open command is not working (command not found).

I'm running Ubuntu 19.04 with yubikey-luks installed from a system repo.

**Comment by Vincent43** [comment]
Debian/Ubuntu package puts `yubikey-luks-open` [in wrong dir](yubikey-luks-open). You can fix it with `sudo ln -s /usr/lib/yubikey-luks /usr/bin/yubikey-luks`.

**Comment by bungabunga** [comment]
Thank you so much! Who's in charge of the ubuntu package - do you think I should leave this issue here open?

**Comment by Vincent43** [comment]
Sorry, I used broken link above, the correct one is https://salsa.debian.org/auth-team/yubikey-luks/merge_requests/1

Ubuntu borrows packages from debian and debian is frozen before next stable release so they can't fix it now (and the fix won't make it to Debian 10). If debian fixes it in near future in unstable branch then the fix may come to Ubuntu 19.10. Either way there is nothing we can do here as the issue is already reported o debian in link I posted.

**Comment by bungabunga** [comment]
Thank you for your detail explanation, things are clearer now!

I hope you don't mind if I ask you an unrelated question: I intended to test using LUKS container (not a boot partition) with Yubikey as a 2FA as a secure vault. Do you know what commands should I use to
1. add Yubikey as a 2FA with challenge:response password to already existing LUKS container
2. decrypt that container via Yubikey and challenge:response password.

(on Yubikey's side everything neccessery is already done because I'm using it also with KeepassX.)

Thanks!

**Comment by Vincent43** [comment]
> add Yubikey as a 2FA with challenge:response password to already existing LUKS container

`yubikey-luks-enroll -d <luks_container_path> -s <slot_number>`

For example:
`yubikey-luks-enroll -d /dev/sda3 -s 7`

> decrypt that container via Yubikey and challenge:response password.

`yubikey-luks-open -d <luks_container_path> -n <container_name>`

For example:
`yubikey-luks-open -d /dev/sda3 -n vault` (luks container will be avalaible at `/dev/mapper/vault`)

You may also look at `/etc/ykluks.cfg` and enable some security enhancements there.

**Comment by bungabunga** [comment]
Thank you so much!
