### ISSUE TITLE
Yubikey headless authentication

### ISSUE THREAD

**Issue by logoldman** [cornelinux/yubikey-luks#55]
This is probably a noob question.  I'm trying to get a "headless" kali box setup with LUKS FDE.  I would like to have the pre-boot authentication only need the yubikey to be present and not need any user input.  I see it mentioned with the ykfde (agherzan/yubikey-full-disk-encryption) package that it can be done.  Can I accomplish this with the cornelinux/yubikey-luks package?  If so how, I'm hitting a stump figuring it out.  Thanks!

**Comment by cornelinux** [comment]
So you want an non-interactive boot? Like, if the yubikey is plugged into the box, the box will boot?
No, this is not possible with the package.

In your case I would recommend to add dropbear to your initramfs and connect via SSH when booting.

**Comment by cornelinux** [comment]
I think this boils down to 1FA, as it is requested in #60 and #65.
