### ISSUE TITLE
Add OnlyKey support

### ISSUE THREAD

**Issue by onlykey** [cornelinux/yubikey-luks#56]
Hi,

We recently implemented HMAC SHA1 in [OnlyKey](https://docs.crp.to), it is fully compatible with Yubikey's HMAC SHA1 challenge and response. We have integrated support with KeePassXC https://github.com/keepassxreboot/keepassxc/pull/3352 and are looking to integrate with other projects as well. The only change required is to allow OnlyKey's USB VID/PID to be used in addition to the already allowed Yubikey USB VID/PIDs. Would you be willing to add support for OnlyKey?

Thanks!

**Comment by cornelinux** [comment]
Hm, then the name of this repo would be a bit misleading ;-)

The initialization would have to be changed. 
Then during boot another chalresp tool for the onlykey would have to query the onlykey.
This either overcomplicate things (querying for either or) or you would have to define during enrollment, which type of key you would want to use.
If you issue a PR, I might actually get active in reviewing PRs again.

**Comment by onlykey** [comment]
@cornelinux It is fully compatible with the yubikey-personalization library. The way to add onlykey support is to call yk_open_key_vid_pid instead of yk_open_first_key. I do see that you don't open a yubikey using this method though. I will have to dig into this a bit more to see if there is an easy way to make this work. I then will be happy to do a PR so you can get active in reviewing these again ;-)

Here is example of how KeepassXC did this - 

https://github.com/keepassxreboot/keepassxc/blob/9b5a46f4b01112e9930c7f17f457e2daaad31505/src/keys/drivers/YubiKey.cpp#L87

Thanks!

**Comment by Vincent43** [comment]
@onlykey the situation here is exactly same as in https://github.com/agherzan/yubikey-full-disk-encryption/issues/56#issuecomment-546597123

**Comment by cornelinux** [comment]
Sorry, we have a lot of other things on the plate. Also I am missing a key to do any testing - if I had time at all.

**Comment by PwnKitteh** [comment]
Hi,
Sorry for dredging up this old issue. I'm trying to use my onlykey to unlock my LUKS volume as 2FA, and this was the closest thing I found compatible with my debian systems. From my understanding and previous interactions with the onlykey community, it's a more secure and MUCH more FOSS friendly ecosystem. My bash skills are unfortunately still quite a bit below the levels required of this type of project lol. 

Is there any way I could convince you to try adding onlykey support?

Thanks! ;)

**Comment by onlykey** [comment]
@PwnKitteh Have you tried this - https://github.com/shimunn/fido2luks

**Comment by Vincent43** [comment]
> Is there any way I could convince you to try adding onlykey support?

It's the yubico developers you need to convince to add cmdline support for non-yubico keys in yubikey-personalization. There is nothing this one project can do on its own.

**Comment by PwnKitteh** [comment]
> @PwnKitteh Have you tried this - https://github.com/shimunn/fido2luks
I hadn't actually heard of the fido2luks project, I'll take a look into that. Thanks!

> It's the yubico developers you need to convince to add cmdline support for non-yubico keys in yubikey-personalization. There is nothing this one project can do on its own.
Yup, this is the conclusion I came to after I left that comment. I started picking apart how the script interacts with ykpersonalize and then the dependencies in ykcore, and it's definitely their library that's the problem. 
Adding the onlykey PID is easy, but getting both yubikey and onlykey (and additionally adding support for any other possible hardware tokens that might need to be added later) is more difficult without changing anything major, and keeping the code clean. I was about halfway finished with a patch around 2am last night, but my code looks awful and isn't an elegant solution. I'll be taking a look at fido2luks next I guess. 

Anyways, thanks for the responses guys. I appreciate it.

**Comment by cornelinux** [comment]
@PwnKitteh I think it would be great to have one solution, that could handle Yubikeys, Onlykeys and other 2nd factors. Then you could in a larger setup mix and match the available keys and manage them like with privacyidea.
But imho in this case LUKS itself would have to extend its API and allow for assymmetric key slots and then this could be achieved by providing plugins that do not need to tweak the existing scripts but as the name indicates... ...plug in.

**Comment by Vincent43** [comment]
It's worth notig that systemd 248+ gained [support for unlocking LUKS with FIDO2 keys](http://0pointer.net/blog/unlocking-luks2-volumes-with-tpm2-fido2-pkcs11-security-hardware-on-systemd-248.html) natively without additional tools.

**Comment by cornelinux** [comment]
By scanning over the link - do I see this correctly that unlocking LUKS with FIDO2 means one-factor-authentication with a security (FIDO2) without any knowledge?
The same key, that is probably stored in the notebook bag of the employee?
Does not sound sensible to me for an enterprise setup.

Imho a vast portion of the Linux community has the problem that it only thinks for their own single use: Works well for one well educated user. :-/

**Comment by Vincent43** [comment]
@cornelinux btw, could you merge [this simple fix](https://github.com/cornelinux/yubikey-luks/pull/69) for suspend script?
