### ISSUE TITLE
Is yubikey-luks strong secure?

### ISSUE THREAD

**Issue by asemchenko** [cornelinux/yubikey-luks#58]
Hello

I have read about challenge-response authentication on the Wikipedia and as I understood it is based on pre-shared-key(both laptop and yubikey have the same key into their memory). Thus, if an attacker got physical access to laptop he/she is able to read pre-shared-key from laptop HDD and decrypt the disk. 

Is it true or I just have wrong understanding about this authentication type?

**Comment by Vincent43** [comment]
There is no pre-shared key. 

1. User types `challenge` on device unlock, this `challenge` isn't saved anywhere in memory after that.
2. Yubikey reads `challenge` then calculate `response` which is constructed from `challenge` + `secret key` stored on yubikey (that key isn't retrievable unless yubikey hardware is flawed)
3. Response is passed to cryptsetup which use it to unlock appropriate keyslot to retrieve encryption key and open LUKS device (`response` is discarded after that)
4. Encryption key stays in memory as long as LUKS device is opened. In LUKS1 format root can dump encryption key with simple command, in LUKS2 format dumping encryption key needs some advanced memory scanning.

[Here are some more details](https://github.com/agherzan/yubikey-full-disk-encryption#manual-mode-with-secret-challenge-2fa)

**Comment by asemchenko** [comment]
@Vincent43 I got you, thanks
