### ISSUE TITLE
suspend service does not unmount correctly

### ISSUE THREAD

**Issue by spiralw** [cornelinux/yubikey-luks#68]
I can only suspend my system once after a reboot. The next time I try to suspend, I get the error: 
```
umount: /run/initramfs/dev: target is busy.
umount: /run/initramfs: target is busy.
```

This doesn't happen if I disable the yubikey-luks-suspend service, so I'm guessing it's something related to that

**Comment by Vincent43** [comment]
Please try following:

1. Find `/usr/lib/yubikey-luks/yubikey-luks-suspend` file and open in text editor
2. Find` mountpoint -q "${INITRAMFS_DIR}${p}" && umount "${INITRAMFS_DIR}${p}"` [line](https://github.com/cornelinux/yubikey-luks/blob/master/yubikey-luks-suspend#L51).
3. Add `-l` option to `umount` call like `mountpoint -q "${INITRAMFS_DIR}${p}" && umount -l "${INITRAMFS_DIR}${p}"`
4. Retest suspend again

**Comment by spiralw** [comment]
It works with that patch, thank you :+1:

**Comment by Vincent43** [comment]
Thx for testing. PR opened here: https://github.com/cornelinux/yubikey-luks/pull/69

**Comment by D0n1elT** [comment]
Im having a similar problem: 

```
umount: /run/initramfs: target is busy.
Press ENTER to continue.

/usr/lib/yubikey-luks/yubikey-luks-suspend: Zeile 64: BIND_MOUNTED ist nicht gesetzt.
umount: /run/initramfs: target is busy.
Press ENTER to continue.
```

This also doesn't happen if I disable the yubikey-luks-suspend service..
I built the latest git version.
