### ISSUE TITLE
YUBIKEY_CHALLENGE Not working?

### ISSUE THREAD

**Issue by r7xf** [cornelinux/yubikey-luks#85]
First, thanks for all the awesome work that went and goes into making this.

Everything works except:
The issue is that YUBIKEY_CHALLENGE="mypassword" is not working as expected.
I am always asked for my password and having this line there or not does not make a difference for me.
Am I missing anything?

**Comment by Vincent43** [comment]
This functionality was added in https://github.com/cornelinux/yubikey-luks/commit/79677deac82a1d6eed852dc7a57c3a8f2106c0a0 and I think debian/ubuntu  didn't updated their [packages](https://salsa.debian.org/auth-team/yubikey-luks) yet to contain it.

You would need to build this package from [source](https://github.com/cornelinux/yubikey-luks#install-package).

**Comment by r7xf** [comment]
Thanks for getting back to me. That is unfortunately that it is not actively maintained by Debian nor Ubuntu.
Unfortunately building it myself results in:

---BEGIN---
user@debian:~/Bulk/yubikey-luks$ make builddeb NO_SIGN=1
make debianize
make[1]: Entering directory '/home/user/Bulk/yubikey-luks'
rm -fr DEBUILD
mkdir -p DEBUILD/yubikey-luks-0.5.1
cp -r * DEBUILD/yubikey-luks-0.5.1 || true
cp: cannot copy a directory, 'DEBUILD', into itself, 'DEBUILD/yubikey-luks-0.5.1/DEBUILD'
(cd DEBUILD; tar -zcf yubikey-luks_0.5.1.orig.tar.gz --exclude=yubikey-luks-0.5.1/debian  yubikey-luks-0.5.1)
make[1]: Leaving directory '/home/user/Bulk/yubikey-luks'
(cd DEBUILD/yubikey-luks-0.5.1; debuild -uc -us)
/bin/sh: 1: debuild: not found
make: *** [Makefile:18: builddeb] Error 127
---END---

**Comment by Vincent43** [comment]
You need to install  `devscripts` package.

**Comment by r7xf** [comment]
Thank you very much! Installing devscripts (and dh-exec) allowed me to build it.
Building it allowed me to install with the latest code, and now it's allowing me to make use of the "YUBIKEY_CHALLENGE".
Circle is round, problem fixed :-) Thanks again and I wish you all the best.
