### ISSUE TITLE
1fa not working with Ubuntu 23.10

### ISSUE THREAD

**Issue by zoof** [cornelinux/yubikey-luks#91]
I'm trying to get 1fa to work with Ubuntu but there seems to be some problem.  Booting with the Yubikey installed still requires that I type the challenge password.  For what it is worth, I have a Yubikey 4.

Following is my `/etc/ykluks.cfg` file:
```
# If you change this file, you need to run 
#   update-initramfs -u
WELCOME_TEXT="Please insert yubikey and press enter or enter a valid passphrase"
# Set to "1" if you want both your password and Yubikey response be bundled together and writtent to key slot.
CONCATENATE=0
# Set to "1" if you want to hash your password with sha256.
HASH=0
YUBIKEY_CHALLENGE="<password>"
```

My only change from the package supplied configuration is to set `YUBIKEY_CHALLENGE`.  Is there some error in my file or is this a bug?

**Comment by Vincent43** [comment]
ubuntu/debian package in repository was never updated to version that contains 1fa feature. You need to build the package from here on github and install it in order to use the feature. See also https://github.com/cornelinux/yubikey-luks/issues/85

**Comment by zoof** [comment]
Many thanks!  The updated package worked!
